/**
 * Fixture de regresión: los 45 riesgos de la matriz real
 * `Matriz de Riesgo Mantto Planta Chancado.xlsx` (área Mantenimiento
 * Chancador), con los valores **que calculó el Excel**.
 *
 * ⚠️ Generado desde el documento original. No editar a mano: si el motor
 * discrepa de estos valores, el que está mal es el motor. Este archivo es la
 * definición operativa de "reproducir correctamente la metodología".
 *
 * Cobertura: 1–18 controles por riesgo.
 */

export interface ControlFixture {
  calidad: string;
  jerarquia: string;
  /** Eficacia que calculó el Excel. */
  eficacia: string;
}

export interface RiesgoFixture {
  /** Fila del bloque en la planilla, para localizarlo al depurar. */
  fila: number;
  numero: string;
  categoria: string;
  exposicion: number;
  posibilidad: number;
  severidad: number;
  /** Valores que calculó el Excel. */
  probabilidad: number;
  resultado: number;
  nivelInicial: string;
  nivelActual: string;
  controles: ControlFixture[];
}

export const MATRIZ_CHANCADO: RiesgoFixture[] = [
  {
    fila: 8,
    numero: '1',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 3,
    resultado: 15,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 9,
    numero: '2',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 27,
    numero: '3',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 5,
    resultado: 25,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 40,
    numero: '4',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 4,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
    ],
  },
  {
    fila: 51,
    numero: '5',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 3,
    resultado: 15,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 62,
    numero: '6',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 5,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 80,
    numero: '7',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 5,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 83,
    numero: '8',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 90,
    numero: '9',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 3,
    severidad: 4,
    probabilidad: 2,
    resultado: 8,
    nivelInicial: 'ACEPTABLE CON REVISIÓN',
    nivelActual: 'ACEPTABLE',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 94,
    numero: '10',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 3,
    severidad: 1,
    probabilidad: 3,
    resultado: 3,
    nivelInicial: 'BAJA',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 95,
    numero: '11',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 98,
    numero: '12',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 103,
    numero: '13',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 110,
    numero: '14',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 3,
    probabilidad: 3,
    resultado: 9,
    nivelInicial: 'ACEPTABLE CON REVISIÓN',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 114,
    numero: '15',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 3,
    severidad: 2,
    probabilidad: 3,
    resultado: 6,
    nivelInicial: 'BAJA',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 115,
    numero: '16',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 119,
    numero: '17',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 3,
    resultado: 9,
    nivelInicial: 'ACEPTABLE CON REVISIÓN',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 121,
    numero: '18',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 3,
    resultado: 15,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 127,
    numero: '19',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 137,
    numero: '20',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 153,
    numero: '21',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 169,
    numero: '22',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 174,
    numero: '23',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 183,
    numero: '24',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 187,
    numero: '25',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 199,
    numero: '26',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 3,
    resultado: 15,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 208,
    numero: '27',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 223,
    numero: '28',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 227,
    numero: '29',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 3,
    severidad: 4,
    probabilidad: 2,
    resultado: 8,
    nivelInicial: 'ACEPTABLE CON REVISIÓN',
    nivelActual: 'ACEPTABLE',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 230,
    numero: '30',
    categoria: 'Seguridad',
    exposicion: 5,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 235,
    numero: '31',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 240,
    numero: '32',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 246,
    numero: '33',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 2,
    probabilidad: 4,
    resultado: 8,
    nivelInicial: 'ACEPTABLE CON REVISIÓN',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 249,
    numero: '34',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 2,
    severidad: 5,
    probabilidad: 5,
    resultado: 25,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 252,
    numero: '35',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 256,
    numero: '36',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 3,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '3. Señalización/ Advertencias/ Alarma',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 258,
    numero: '37',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 4,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 259,
    numero: '38',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 3,
    severidad: 2,
    probabilidad: 3,
    resultado: 6,
    nivelInicial: 'BAJA',
    nivelActual: 'BAJA',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 262,
    numero: '39',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 4,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 263,
    numero: '40',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 4,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 264,
    numero: '41',
    categoria: 'Seguridad',
    exposicion: 4,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 3,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 266,
    numero: '42',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'INACEPTABLE',
    controles: [
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'C. Menor a 50%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción No Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 282,
    numero: '43',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 2,
    severidad: 4,
    probabilidad: 4,
    resultado: 16,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'SUSTANCIAL',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '4. Ingeniería',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
  {
    fila: 285,
    numero: '44',
    categoria: 'Seguridad',
    exposicion: 3,
    posibilidad: 3,
    severidad: 3,
    probabilidad: 4,
    resultado: 12,
    nivelInicial: 'SUSTANCIAL',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '1. EPP',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
    ],
  },
  {
    fila: 287,
    numero: '45',
    categoria: 'Seguridad',
    exposicion: 2,
    posibilidad: 3,
    severidad: 5,
    probabilidad: 4,
    resultado: 20,
    nivelInicial: 'INACEPTABLE',
    nivelActual: 'ACEPTABLE CON REVISIÓN',
    controles: [
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'A. Mayor 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Eficaz',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
      {
        calidad: 'B. 50% y 80%',
        jerarquia: '2. Administrativo/ Procedimientos/ Capacitación',
        eficacia: 'Control/Acción Satisfactorio',
      },
    ],
  },
];
